name: Simple Static Deploy to Production

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy index.html to server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ variables.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ variables.REMOTE_HOST }}
          REMOTE_USER: ${{ variables.REMOTE_USER }}
          TARGET: "/var/www/test/protfolio"          # Or your target path
          SOURCE: "."                      # Root folder — uploads index.html
          ARGS: "-avz --delete"            # Deletes files not in source
